### ISSUE TITLE
"MVPリリース"レビュー依頼

### ISSUE THREAD

**Issue by kenty0102** [kenty0102/menu_maker#138]
## 各種情報
サービス名：Menu Maker
サービスURL：https://menu-maker-app.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] ユーザー認証（ユーザー登録、ログイン、ログアウト、パスワードリセット）
- [ ] レシピ検索（クックパッドのサイトへのリンクを表示）
- [ ] レシピの自動保存機能（URL入力、クックパッドのみ）
- [ ] レシピの手動保存（作成）機能
- [ ] 保存したレシピの編集、削除機能
- [ ] メニュー表の作成機能

## READMEレビュー時から変更した機能
- 開発途中で追加した機能
  - [ ] メニュー表の編集、削除機能
  - [ ] メニュー表の一覧
  - [ ] レシピの一覧
  - [ ] 問い合わせ機能

## サービスイメージがわかるようなスクリーンショット等
- トップ画面（ログイン前）
![Image](https://github.com/user-attachments/assets/199845fd-3cc3-4e8e-9ec0-d0dab4fe6779)
- ユーザー新規登録画面
![Image](https://github.com/user-attachments/assets/54cb0386-a843-4e37-b136-cae427bc96a6)
- ログイン画面
![Image](https://github.com/user-attachments/assets/18458457-4a14-4e60-a80c-50305e98f87e)
- トップ画面（ログイン後）
![Image](https://github.com/user-attachments/assets/c0e3e58d-789d-47f7-9ac1-0e0b29d1c499)
- レシピ保存方法選択画面
![Image](https://github.com/user-attachments/assets/34fc9cb0-ecc3-41c9-aeb7-3b607ea3e01d)
- レシピ手動保存画面
![Image](https://github.com/user-attachments/assets/beb54837-3e2e-40c8-9fc3-d73487c8461c)
- メニュー表作成画面
![Image](https://github.com/user-attachments/assets/e03fb777-8fb3-46c9-ac80-cace607e9026)
- メニュー表詳細画面
![Image](https://github.com/user-attachments/assets/218f0e01-7785-48d2-b741-d38e3de97f37)

現時点で、管理画面など通常ユーザーが触れない機能はありません。

**Comment by kenchasonakai** [comment]
LGTMです！
