### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by kenty0102** [kenty0102/menu_maker#69]
### 概要
このアプリは、クックパッド、DELISH KITCHEN、クラシルのレシピを検索・保存し、自作メニュー表を簡単に作成するための家庭向けWebアプリです。  
検索したレシピはURLの入力で自動保存でき、その他のレシピも手動で追加・編集可能で、選べるデザインでオリジナルメニュー表が作成できます。  
完成したメニュー表は画像として保存やSNSでシェアできます。

#### MVPリリース時
- [ ] ユーザー認証（ユーザー登録、ログイン、ログアウト、パスワードリセット）
- [ ] ユーザー情報変更（ユーザー名、メールアドレス、パスワード）
- [ ] レシピ検索（クックパッドのサイトへのリンクを表示）
- [ ] レシピの自動保存機能（URL入力、クックパッドのみ）
- [ ] レシピの手動保存（作成）機能
- [ ] 保存したレシピの編集、削除機能
- [ ] メニュー表の作成機能
- [ ] 問い合わせ機能
#### 本リリース
- [ ] レシピ検索（DELISH KITCHEN、クラシルへのリンク表示を追加）
- [ ] レシピの自動保存機能（URL入力、DELISH KITCHEN、クラシルを追加）
- [ ] 保存したレシピの検索機能
- [ ] メニュー表のデザイン選択機能
- [ ] メニュー表の編集機能
- [ ] メニュー表の画像化機能
- [ ] アプリのSNSシェア機能

### 必要なページ
- [ ] トップページ
- [ ] ユーザー登録ページ
- [ ] ログインページ
- [ ] パスワードリセット申請ページ
- [ ] 新しいパスワードの設定ページ
- [ ] ユーザー情報編集ページ（ユーザー名変更ページ、メールアドレス変更ページ、パスワード変更ページ）
- [ ] レシピ検索ページ（URLリンク）
- [ ] レシピ保存ページ（自動保存）
- [ ] 手動保存ページ
- [ ] 保存したレシピ一覧ページ
- [ ] レシピの詳細ページ
- [ ] レシピの編集ページ
- [ ] メニュー表作成ページ
- [ ] メニュー表確認ページ
- [ ] メニュー表編集ページ
- [ ] 画像化ページ
- [ ] 問い合わせ入力ページ
- [ ] 問い合わせ内容確認ページ
- [ ] 問い合わせ完了ページ
- [ ] 利用規約ページ
- [ ] プライバシーポリシーページ

**Comment by Mariko222** [comment]
ご提出ありがとうございます。
概ね良さそうですが、以下気になった点コメントさせて頂きます。
***
ストーリーポイントが5のissueがいくつか見受けられますが、箇条書されている中で分割できそうなものがあれば、分割を検討してストーリーポイントが小さくなるようにした方が良いかなと思いました。
例えば以下トップページ作成の例ですと、１〜３つ目の最低限の実装と4〜５つ目で分けられるような気がしました。

> viewの作成
>  ルーティング設定
>  コントローラー作成
>  レシピ検索、レシピ保存、レシピ一覧、メニュー作成の各ページへのリンク設置
>  アプリケーションの説明文作成

ご確認よろしくお願いします。

**Comment by kenty0102** [comment]
返信コメントありがとうございます。

ストーリーポイント5のissueについて再度検討し、下記の通り修正しました。
よろしくお願いいたします。
### 修正点
#### トップページ作成
「トップページ作成」、「トップページにリンクと説明分追加」に分割
#### レシピの自動保存機能
「レシピの自動保存機能の実装準備」、「レシピの自動保存機能」に分割
#### レシピの手動保存機能
「レシピ手動保存の基本的な実装」、「レシピ手動保存時のバリデーション、フラッシュメッセージ設定」に分割
#### AWS S3導入
「S3バケットの設定」、「carriewaveによるファイル保存設定（AWS）」、「アップロードテスト（AWS,carrierwave）」に分割
#### 保存したレシピ一覧ページ作成
「保存したレシピ一覧ページの作成」、「レシピ一覧ページにリンク設置」に分割
#### メニュー表の作成機能
「メニュー表の作成機能実装準備」、「メニュー表作成機能の実装」に分割
#### 問い合わせ機能
「問い合わせ機能実装準備」、「問い合わせ機能実装」に分割

**Comment by tarakish** [comment]
修正確認しました。LGTMです！
MVPリリースに向けて開発頑張ってください！
